version: "3.2"
services:
  mysql:
    image: mysql:${MYSQL_VERSION:-latest}
    restart: unless-stopped
    ports:
      - "3306:3306"
    expose:
      # Opens port 3306 on the container
      - '3306'
    volumes:
            - data:/var/lib/mysql
    networks:
      - backend
    environment:
      MYSQL_ROOT_PASSWORD: "${DB_ROOT_PASSWORD}"
      MYSQL_DATABASE: "${DB_NAME}"
      MYSQL_USER: "${DB_USERNAME}"
      MYSQL_PASSWORD: "${DB_PASSWORD}"
    container_name: mysql

  mysql2:
    image: mysql:${MYSQL_VERSION:-latest}
    restart: unless-stopped
    ports:
      - "3307:3306"
    expose:
      # Opens port 3306 on the container
      - '3306'
    volumes:
            - data:/var/lib/mysql2
    networks:
      - backend
    environment:
      MYSQL_ROOT_PASSWORD: "${DB_ROOT_PASSWORD2}"
      MYSQL_DATABASE: "${DB_NAME2}"
      MYSQL_USER: "${DB_USERNAME2}"
      MYSQL_PASSWORD: "${DB_PASSWORD2}"
    container_name: mysql2
networks:
  backend:
volumes:
    data:
